# Generated by Django 4.1.3 on 2022-12-27 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyProfile',
        ),
    ]
